### ISSUE TITLE
Does not work on iOS

### ISSUE THREAD

**Issue by dimitryvolkov** [idobh2/audioStreamer#1]

**Comment by idobh2** [comment]
Unfortunately, iOS browsers don't support WebRTC out-of-the-box. 
You can use the cordova plugin that extends this functionality into the webview (https://github.com/eface2face/cordova-plugin-iosrtc)

Or work with Chrome for iOS, which i think suports WebRTC

**Comment by dimitryvolkov** [comment]
I tested your library using cordova-plugin-iosrtc and it seems your library performs rather poorly, please consider stopping its development
